global:
  host: "chart-example.local"
  # Change this is your ingress is exposed with port other than 443, 80, like 8080 for instance
  port: ""
  enableTLS: false
  extraBackendEnvs:
    - name: SECRET_KEY
      value: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U

postgresql:
  host: "192.168.1.8"
  port: "5432"
  username: "postgres"
  password: "difyai123456"
  database: "dify"

redis:
  host: "192.168.1.8"
  port: "6379"
  password: "difyai123456"
  database: "1"

weaviate:
  host: "192.168.1.8"
  port: "8080"
  apiKey: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"

minio:
  host: "192.168.1.8"
  port: "9000"
  bucketName: "dify"
  accessKey: "admin"
  secretKey: "changeme"

ingress:
  enabled: true
  className: "nginx"
